const LANGUAGES = {
    es: {
        "Ritmo": "Ritmo",
        "Melodía": "Melodía",
        "Dinámica": "Dinámica",
        "Instrumentación": "Instrumentación",
        "Composición": "Composición",
        "Lyrics": "Letras",
        "BPM": "BPM",
        "Compás": "Compás",
        "Frase": "Frase",
        "Vaciar": "Vaciar",
        "VaciarLabel": "Vaciar →",
        "Empezar": "Aceptar",
        "Tonalidad": "Tonalidad",
        "Borrar compás": "Del",
        "Deshacer": "Deshacer",
        "Rehacer": "Rehacer",
        "Soprano": "Soprano",
        "Contralto": "Contralto",
        "Tenor": "Tenor",
        "Bajo": "Bajo",
        "Loop OFF": "Repetir OFF",
        "Loop ON": "Repetir ON",
        "Resumen": "Resumen",
        "Editor de Paleta de Tonalidades": "Editor de Paleta de Tonalidades",
        "ZONA DE ARMONIZACIÓN": "ZONA DE ARMONIZACIÓN",
        "Armonizar desde esta voz": "Armonizar desde esta voz",
        "Ajustar a escala": "Ajustar a escala",
        "Onda (Modulación)": "Onda (Modulación)",
        "Aplicar": "Aplicar",
        "Editor de Lyrics": "Editor de Letras",
        "Configuración de lyrics próximamente...": "Configuración de letras próximamente...",
        "Mezclador de Volúmenes": "Mezclador de Volúmenes",
        "Volumen General": "Volumen General",
        "Mezcla por Pistas": "Mezcla por Pistas",
        "Configuración de Instrumentos": "Configuración de Instrumentos",
        "Instrumento General": "Instrumento General",
        "Composición por compases": "Composición por compases",
        "Nomenclatura": "Nomenclatura",
        "Armonía Diatónica": "Armonía Diatónica",
        "Métrica": "Métrica",
        "Key": "Clave",
        "Escala": "Escala",
        "Título de la composición": "Título de la composición",
        "Activada": "Activada",
        "Desactivada": "Desactivada",
        "Mayor": "Mayor",
        "Menor": "Menor",
        "Cromática": "Cromática",
        "EmpezarLabel": "Empezar →",
        "Cant:": "Cant:",
        "Trasponer": "Trasponer",
        "Duplicar": "Duplicar",
        "Semitonos": "Semitonos",
        "Estructura": "Estructura",
        "Aleatorio": "Aleatorio",
        "Cíclico": "Cíclico",
        "Solo Selecc.": "Solo Selecc.",
        "Todas Audibles": "Todas Audibles",
        "ONDA TOTAL": "ONDA TOTAL",
        "Onda Ritmo": "Onda Ritmo",
        // Tarareo panel translations
        "Hum (Rhythm)": "Tarareo (Ritmo)",
        "Algorithm information": "Información sobre el algoritmo",
        "Pattern Selection Algorithm": "Algoritmo de Selección de Patrones",
        "Current voice:": "Voz actual:",
        "Voice Configuration:": "Configuración por Voz:",
        "Random, normal time": "Random, tiempo normal",
        "Random,": "Random,",
        "time descent (×0.5)": "descenso de tiempos (×0.5)",
        "Phonetic, normal time": "Phonetic, tiempo normal",
        "Phonetic,": "Phonetic,",
        "Random:": "Random (Aleatoria):",
        "Completely random selection. Maximum variety.": "Selección completamente al azar. Máxima variedad.",
        "Phonetic:": "Phonetic (Fonética):",
        "Analyzes each syllable:": "Analiza cada sílaba:",
        "Long consonants → long notes": "Consonantes largas → notas largas",
        "Long vowels/diphthongs → long notes": "Vocales largas/diptongos → notas largas",
        "Simple syllables → short notes": "Sílabas simples → notas cortas",
        "Time descent:": "Descenso de tiempos:",
        "Durations are halved (quarter → eighth, etc.)": "Las duraciones se reducen a la mitad (negra → corchea, etc.)",
        "New Option: Generate Melody": "Nueva Opción: Generar Melodía",
        "Calculates melodic movement according to consonants.": "Calcula el movimiento melódico según las consonantes.",
        "Post-vowel consonants:": "Consonantes post-vocal:",
        "Raises pitch (e.g. 'trans' ↑).": "Sube el tono (ej. \"trans\" ↑).",
        "Pre-vowel consonants:": "Consonantes pre-vocal:",
        "Lowers pitch (e.g. 'bla' ↓).": "Baja el tono (ej. \"bla\" ↓).",
        "Diphthongs:": "Diptongos:",
        "Amplify the movement.": "Amplifican el movimiento.",
        " Automatic:": " Automático:",
        "Algorithm changes automatically according to active voice.": "El algoritmo cambia automáticamente según la voz activa.",
        "Strategy:": "Estrategia:",
        "1. Strict Syllabic (Random)": "1. Silábica Estricta (Random)",
        "2. Grouped Syllabic (Random)": "2. Silábica Agrupada (Random)",
        "3. Smart Phonetic (Grouped)": "3. Fonética Inteligente (Agrupada)",
        "4. Smart Strict (Ungrouped)": "4. Estricta Inteligente (No Agrupada)",
        "5. Double Random (S ≠ T)": "5. Doble Random (S ≠ T)",
        "Generate Melody (Consonants)": "Generar Melodía (Consonantes)",
        "Type your rhythm... (e.g. ta ta ta ta)": "Escribe tu ritmo... (ej: ta ta ta ta)",
        "POS": "POS",
        "COMP": "COMP",
        "Copiar": "Copiar",
        "Pegar": "Pegar",
        "Trasponer": "Trasponer",
        "Ir a posición de cursor": "Ir a posición de cursor",
        "Ir a compás": "Ir a compás",
        "Modo: Dependiente (armonía diatónica)": "Modo: Dependiente (armonía diatónica)",
        "Modo: Independiente (manual)": "Modo: Independiente (manual)",
        "Borrar compás o compases seleccionados": "Borrar compás o compases seleccionados",
        " Compositor de Estructuras": " Compositor de Estructuras",
        "Define la estructura (letras A, B, C...)": "Define la estructura (letras A, B, C...)",
        "Generar": "Generar",
        "Frases Disponibles:": "Frases Disponibles:",
        " Editor de Letras": " Editor de Letras",
        "Escribe una sílaba por nota. Usa espacios para separar.": "Escribe una sílaba por nota. Usa espacios para separar.",
        "Guardar Letra": "Guardar Letra",
        "Ej: ABBC": "Ej: ABBC",
        "Ej: La la la...": "Ej: La la la...",
        "Clic para descargar, doble clic para editar": "Clic para descargar, doble clic para editar",
        "Variaciones": "Variaciones",
        "Actualizar": "Actualizar",
        "Acc:": "Acc:",
        "Modo:": "Modo:",
        "Bio:": "Bio:",
        "Cnt:": "Cnt:",
        "Amp:": "Amp:",
        "Freq:": "Freq:",
        "Fma:": "Fma:",
        "Mn:": "Mn:",
        "Mx:": "Mx:",
        " Onda": " Onda",
        " Dinámica (Volumen)": " Dinámica (Volumen)",
        "Generar": "Generar",
        "Armonizar desde esta voz": "Armonizar desde esta voz",
        "Ajustar a escala": "Ajustar a escala",
        " Onda (Modulación)": " Onda (Modulación)",
        "Modif": "Modif",
        "Generar": "Generar",
        "Seleccionar número de compases": "Seleccionar número de compases",
        "Todo": "Todo",
        "Img2MelodyTitle": "Img2Melody",
        "ImgMelodyOpen": "Abrir",
        "ImgMelodyInfoTitle": "Información sobre el algoritmo",
        "ImgMelodyDuration": "Duración:",
        "ImgMelodyRhythm": "Ritmo:",
        "Sensible (Dinámico + Silencios Trilipi)": "Sensible (Dinámico + Silencios Trilipi)",
        "Relativa (Sensible + Tono Relativo)": "Relativa (Sensible + Tono Relativo)",
        "Literal (Color a Compás RGB)": "Literal (Color a Compás RGB)",
        "Uniforme (Percusión B/C)": "Uniforme (Percusión B/C)",
        "Basado en Brillo (Trilipi)": "Basado en Brillo (Trilipi)",
        "Completo (Dinámico + Silencios/Rel.)": "Completo (Dinámico + Silencios/Rel.)",
        "Arpegio (Escalera de Extremos)": "Arpegio (Escalera de Extremos)",
        "ImgMelodySettings": "Ajustes Sensibles y Estructura",
        "ImgMelodyStructure": "Estructura (Intro - Medio - Fin):",
        "ImgMelodySil": "Sil:",
        "ImgMelodyVol": "Vol:",
        "ImgMelodyGenerate": " Generar",
        "ImgMelodyLogicTitle": " Lógica Polifónica:",
        "Eje X": "Eje X",
        "Tiempo": "Tiempo",
        "Eje Y": "Eje Y",
        "Voces (SATB)": "Voces (SATB)",
        "Brillo": "Brillo",
        "Altura": "Altura",
        "Negro": "Negro",
        "Silencio (si activo)": "Silencio (si activo)",
        "Blanco": "Blanco",
        "Nota Larga (si activo)": "Nota Larga (si activo)",
        "Int:": "Int:",
        "Det:": "Det:",
        "ImgMelodyDescArpegio": "Intervalo S→A / T→B (pasos de escala) y volumen base.",
        "ImgMelodyDescLiteral": "Controla la sensibilidad de detalle para agrupar colores (- detalle = acordes, + detalle = arpegios rápidos).",
        "ImgMelodyDescSensible": "Define umbral de oscuridad (silencio) y base de volumen.",
        "compases": "compases",
        "Cortar": "️ Cortar",
        "Cortar compases seleccionados": "Cortar compases seleccionados",
        "Copiar compases seleccionados": "Copiar compases seleccionados",
        "Pegar compases copiados": "Pegar compases copiados",
        "Seleccionar todos los compases": "Seleccionar todos los compases",
        "Añadir un compás a la selección": "Añadir un compás a la selección",
        "Eliminar un compás de la selección": "Eliminar un compás de la selección",
        "Duplicar": "Duplicar",
        "Duplicar compases seleccionados": "Duplicar compases seleccionados",
        "Variaciones": "Variaciones",
        "Generar variaciones de los compases seleccionados": "Generar variaciones de los compases seleccionados",
        "Opciones de Variación": "Opciones de Variación",
        "▶ Variaciones Tonales (Notas)": "▶ Variaciones Tonales (Notas)",
        "Ninguna:": "Ninguna:",
        "Las notas musicales originales se mantienen intactas.": "Las notas musicales originales se mantienen intactas.",
        "Sutil (Baladas / Coros):": "Sutil (Baladas / Coros):",
        "Movimientos de +/- 1 grado. Notas muy cerca de la original.": "Movimientos de +/- 1 grado. Notas muy cerca de la original.",
        "Normal (Estándar):": "Normal (Estándar):",
        "Saltos intermedios (1 a 3 grados). Familiaridad y sorpresa.": "Saltos intermedios (1 a 3 grados). Familiaridad y sorpresa.",
        "Agresivo (Arpegios / Solos):": "Agresivo (Arpegios / Solos):",
        "Saltos extensos (4 a 5 grados). Transforma la melodía.": "Saltos extensos (4 a 5 grados). Transforma la melodía.",
        "Final (Resolutiva):": "Final (Resolutiva):",
        "Obliga a que la melodía termine (resuelva) en la nota tónica.": "Obliga a que la melodía termine (resuelva) en la nota tónica.",
        "▶ Variaciones Dinámicas (Volumen)": "▶ Variaciones Dinámicas (Volumen)",
        "El volumen (dinámica) original se mantiene intacto.": "El volumen (dinámica) original se mantiene intacto.",
        "Humanizar:": "Humanizar:",
        "Pequeñas variaciones aleatorias para dar un toque humano.": "Pequeñas variaciones aleatorias para dar un toque humano.",
        "Crescendo:": "Crescendo:",
        "Aumenta progresivamente el volumen desde el principio al fin.": "Aumenta progresivamente el volumen desde el principio al fin.",
        "Diminuendo:": "Diminuendo:",
        "Disminuye progresivamente el volumen desde el principio al fin.": "Disminuye progresivamente el volumen desde el principio al fin.",
        "Acentuación (Golpe):": "Acentuación (Golpe):",
        "Marca con un volumen muy fuerte los inicios de cada compás.": "Marca con un volumen muy fuerte los inicios de cada compás.",
        "Configurar opciones de variación": "Configurar opciones de variación",
        "▶ Variaciones de Tiempo (Duración)": "▶ Variaciones de Tiempo (Duración)",
        "El ritmo original se mantiene intacto.": "El ritmo original se mantiene intacto.",
        "Rotación:": "Rotación:",
        "Desplaza la secuencia de duraciones.": "Desplaza la secuencia de duraciones.",
        "Permutación:": "Permutación:",
        "Reordena aleatoriamente las duraciones dentro del compás.": "Reordena aleatoriamente las duraciones dentro del compás.",
        "Duración x2:": "Multiplica la duración (doble de lentas).",
        "Duración /2:": "Divide la duración (doble de rápidas).",
        "Partes": "Partes",
        "PartesDesc": "— Ritmos diferenciados por sección",
        "PartesLabel": "Partes:",
        "Densidad:": "Densidad:",
        "Voces:": "Voces:",
        "PartesTitle": "Cada dígito = número de compases de esa parte (ej: 234 → Parte A: 2 compases, Parte B: 3, Parte C: 4)",
        "DensidadTitle": "Cómo variar el número de notas entre partes",
        "Alternado (2↔4↔6…)": "Alternado (2↔4↔6…)",
        "Ascendente (2→4→6…)": "Ascendente (2→4→6…)",
        "Descendente (6→4→2…)": "Descendente (6→4→2…)",
        "Auto (compás actual)": "Auto (compás actual)",
        "VocesTitle": "Rotación de voces silenciadas por parte",
        "Todas suenan": "Todas suenan",
        "2 calladas (rotar)": "2 calladas (rotar)",
        "1 callada (rotar)": "1 callada (rotar)",
        "Solo (3 calladas)": "Solo (3 calladas)",
        "PartesReshuffleTitle": "Elegir nuevos patrones aleatorios manteniendo la estructura",
        "PartesPreviewDefault": "Escribe un número (ej: 234) para ver la previsualización",
        "PartesEmptyWarning": "⚠️ Escribe dígitos 1-9 (ej: 234)",
        "Sin partes": "Sin partes",
        "compExt": "comp",
        "compases insertados": "compases",
        "PartesEmptyWarning": "⚠️ Escribe dígitos 1-9 (ej: 234)",
        "Sin partes": "Sin partes",
        "compExt": "comp",
        "compases insertados": "compases",
        "insertados en pos.": "insertados en pos.",
        "partesExt": "partes",
        "Rand": "Rand",
        "Generación:": "Generación:",
        "GeneracionTitle": "Elige si generar solo ritmo, añadir melodía o también dinámica",
        "Solo Ritmo": "Solo Ritmo",
        "Ritmo y Melodía": "Ritmo y Melodía",
        "n-notas": "{n} notas",
        "Ciclo (Notas):": "Ciclo (Notas):",
        "Amp (Max):": "Amp (Max):",
        "Notas:": "Notas:",
        "Seleccionar {n} nota(s)": "Seleccionar {n} nota(s)",
        "Ver variaciones de silencios para 8 notas": "Ver variaciones de silencios para 8 notas",
        "Silencio de Redonda": "Silencio de Redonda",
        "Rest": "Silencio",
        "AlertHarmonize": " Armonizado: {n} compases actualizados desde {v}",
        "AlertChromatic": "️ La escala cromática ya incluye todas las notas. No es necesario ajustar.",
        "AlertScaleAdjust": " Ajustado a escala: {n} notas ajustadas en {m} compases\nVoz: {v}\nEscala: {k} {s}",
        "OndaAmpTitle": "Amplitud máxima en pasos de escala",
        "OndaCycleTitle": "Longitud de ciclo en notas",
        "+ Dinamismo": "+ Dinamismo",
        "MIDIIndependent": "Modo: Independiente",
        "MIDIDependent": "Modo: Dependiente",
        "DuplicateMeasure": "Duplicar compás",
        "SplitVoices": "Separar voces en 4 compases",
        "InvertSelection": "Invertir Selección",
        "DeleteMeasure": "Eliminar compás",
        "Soprano": "Soprano",
        "Contralto": "Contralto",
        "Tenor": "Tenor",
        "Bajo": "Bajo",
        "CompasMidi": "Compás",
        "NotaMidi": "Nota",
        "NoMultiVoice": "Este compás no tiene estructura de múltiples voces",
        "Revert": "Revertir",
        "AddMidi": "Añadir",
        "ApplyMidi": "Aplicar",
        "MuteVoice": "Silenciar {v}",
        "ActivateVoice": "Activar {v}",
        "TooltipX2": "Duplicar notas seleccionadas y reducir duración a la mitad",
        "TooltipDiv2": "Combinar notas seleccionadas (reducir cantidad)",
        "TooltipRotate": "Rotar notas seleccionadas (Pitch + Duración)",
        "PeakMidi": "cima",
        "ValleyMidi": "valle",
        "DeshacerCambios": "Deshacer cambios en este compás",
        "SaveLyrics": "Guardar Letra",
        "UpdateDBI": "Actualizar",
        "Limitador de Volumen": "Limitador de Volumen",
        "Mínimo:": "Mínimo:",
        "Máximo:": "Máximo:",
        "Aplicar Límite": "Aplicar Límite",
        "Voz": "Voz",
        "Nombre": "Nombre",
        "Instrumento": "Instrumento",
        "Nombre de pista": "Nombre de pista",
        "Instrumento General (aplica a todas las voces):": "Instrumento General (aplica a todas las voces):",
        "Arrastra o selecciona un archivo .musicoli": "Arrastra o selecciona un archivo .musicoli",
        "¡Archivo cargado correctamente!": "¡Archivo cargado correctamente!",
        "El archivo no tiene el formato .musicoli o .json válido.": "El archivo no tiene el formato .musicoli o .json válido.",
        "Error al leer el archivo. Asegúrate de que es un JSON / .musicoli válido.": "Error al leer el archivo. Asegúrate de que es un JSON / .musicoli válido.",
        "StrumTitle": "Intensidad de Arpegio",
        "Arpeggio": "Arpegio",
        "Escalas": "Escalas",
        "Acordes": "Acordes",
        "Apply chord to selected notes": "Aplicar acorde a las notas seleccionadas",
        "Tessituras": "Tesituras",
        "Min": "Min",
        "Max": "Max"
    },
    en: {
        "Escalas": "Scales",
        "Acordes": "Chords",
        "Apply chord to selected notes": "Apply chord to selected notes",
        "Ritmo": "Rhythm",
        "Melodía": "Melody",
        "Dinámica": "Dynamics",
        "Instrumentación": "Instruments",
        "Composición": "Composition",
        "Lyrics": "Lyrics",
        "BPM": "BPM",
        "Compás": "Measure",
        "Frase": "Phrase",
        "Vaciar": "Empty",
        "VaciarLabel": "Empty →",
        "Empezar": "Accept",
        "Tonalidad": "Tonality",
        "Borrar compás": "Del",
        "Deshacer": "Undo",
        "Rehacer": "Redo",
        "Soprano": "Soprano",
        "Contralto": "Alto",
        "Tenor": "Tenor",
        "Bajo": "Bass",
        "Loop OFF": "Loop OFF",
        "Loop ON": "Loop ON",
        "Resumen": "Summary",
        "Editor de Paleta de Tonalidades": "Tonality Palette Editor",
        "ZONA DE ARMONIZACIÓN": "HARMONIZATION ZONE",
        "Armonizar desde esta voz": "Harmonize from this voice",
        "Ajustar a escala": "Snap to scale",
        "Onda (Modulación)": "Wave (Modulation)",
        "Aplicar": "Apply",
        "Editor de Lyrics": "Lyrics Editor",
        "Configuración de lyrics próximamente...": "Lyrics configuration coming soon...",
        "Mezclador de Volúmenes": "Volume Mixer",
        "Volumen General": "Master Volume",
        "Mezcla por Pistas": "Track Mix",
        "Configuración de Instrumentos": "Instrument Configuration",
        "Instrumento General": "General Instrument",
        "Composición por compases": "Measure-based Composition",
        "Nomenclatura": "Nomenclature",
        "Armonía Diatónica": "Diatonic Harmony",
        "Métrica": "Time Signature",
        "Key": "Key",
        "Escala": "Scale",
        "Título de la composición": "Composition Title",
        "Activada": "Enabled",
        "Desactivada": "Disabled",
        "Mayor": "Major",
        "Menor": "Minor",
        "Cromática": "Chromatic",
        "EmpezarLabel": "Start →",
        "Cant:": "Amt:",
        "Trasponer": "Transpose",
        "Duplicar": "Duplicate",
        "Semitonos": "Semitones",
        "Estructura": "Structure",
        "Aleatorio": "Random",
        "Cíclico": "Cyclic",
        "Solo Selecc.": "Only Selected",
        "Todas Audibles": "All Audible",
        "ONDA TOTAL": "TOTAL WAVE",
        "Onda Ritmo": "Rhythm Wave",
        "POS": "POS",
        "COMP": "MEAS",
        "Copiar": "Copy",
        "Pegar": "Paste",
        "Trasponer": "Transpose",
        "Ir a posición de cursor": "Go to cursor position",
        "Ir a compás": "Go to measure",
        "Modo: Dependiente (armonía diatónica)": "Mode: Dependent (diatonic harmony)",
        "Modo: Independiente (manual)": "Mode: Independent (manual)",
        "Borrar compás o compases seleccionados": "Delete selected measure(s)",
        " Compositor de Estructuras": " Structure Compositor",
        "Define la estructura (letras A, B, C...)": "Define the structure (letters A, B, C...)",
        "Generar": "Generate",
        "Frases Disponibles:": "Available Phrases:",
        " Editor de Letras": " Lyrics Editor",
        "Escribe una sílaba por nota. Usa espacios para separar.": "Write one syllable per note. Use spaces to separate.",
        "Guardar Letra": "Save Lyrics",
        "Ej: ABBC": "Ex: ABBC",
        "Ej: La la la...": "Ex: La la la...",
        "Clic para descargar, doble clic para editar": "Click to download, double click to edit",
        "Variaciones": "Variations",
        "Actualizar": "Update",
        "Acc:": "Act:",
        "Modo:": "Mode:",
        "Bio:": "Block:",
        "Cnt:": "Cnt:",
        "Amp:": "Amp:",
        "Freq:": "Freq:",
        "Fma:": "Shape:",
        "Mn:": "Mn:",
        "Mx:": "Mx:",
        " Onda": " Wave",
        " Dinámica (Volumen)": " Dynamics (Volume)",
        "Generar": "Generate",
        "Armonizar desde esta voz": "Harmonize from this voice",
        "Ajustar a escala": "Adjust to scale",
        " Onda (Modulación)": " Wave (Modulation)",
        "Modif": "Modify",
        "Generar": "Generate",
        "Seleccionar número de compases": "Select number of measures",
        "Todo": "All",
        "Img2MelodyTitle": "Img2Melody",
        "ImgMelodyOpen": "Open",
        "ImgMelodyInfoTitle": "Algorithm information",
        "ImgMelodyDuration": "Duration:",
        "ImgMelodyRhythm": "Rhythm:",
        "Sensible (Dinámico + Silencios Trilipi)": "Sensitive (Dynamic + Trilipi Rests)",
        "Relativa (Sensible + Tono Relativo)": "Relative (Sensitive + Relative Pitch)",
        "Literal (Color a Compás RGB)": "Literal (RGB Color to Measure)",
        "Uniforme (Percusión B/C)": "Uniform (Percussion Kick/Snare)",
        "Basado en Brillo (Trilipi)": "Brightness Based (Trilipi)",
        "Completo (Dinámico + Silencios/Rel.)": "Full (Dynamic + Silences/Rel.)",
        "Arpegio (Escalera de Extremos)": "Arpeggio (Extremes Ladder)",
        "ImgMelodySettings": "Sensitive Settings & Structure",
        "ImgMelodyStructure": "Structure (Intro - Mid - Outro):",
        "ImgMelodySil": "Sil:",
        "ImgMelodyVol": "Vol:",
        "ImgMelodyGenerate": " Generate",
        "ImgMelodyLogicTitle": " Polyphonic Logic:",
        "Eje X": "X Axis",
        "Tiempo": "Time",
        "Eje Y": "Y Axis",
        "Voces (SATB)": "Voices (SATB)",
        "Brillo": "Brightness",
        "Altura": "Pitch",
        "Negro": "Black",
        "Silencio (si activo)": "Silence (if active)",
        "Blanco": "White",
        "Nota Larga (si activo)": "Long Note (if active)",
        "Int:": "Int:",
        "Det:": "Det:",
        "ImgMelodyDescArpegio": "S→A / T→B Interval (scale steps) and base volume.",
        "ImgMelodyDescLiteral": "Controls detail sensitivity to group colors (- detail = chords, + detail = fast arpeggios).",
        "ImgMelodyDescSensible": "Defines darkness threshold (silence) and base volume.",
        "compases": "measures",
        "Cortar": "️ Cut",
        "Cortar compases seleccionados": "Cut selected measures",
        "Copiar compases seleccionados": "Copy selected measures",
        "Pegar compases copiados": "Paste copied measures",
        "Seleccionar todos los compases": "Select all measures",
        "Añadir un compás a la selección": "Add a measure to selection",
        "Eliminar un compás de la selección": "Remove a measure from selection",
        "Duplicar": "Duplicate",
        "Duplicar compases seleccionados": "Duplicate selected measures",
        "Variaciones": "Variations",
        "Generar variaciones de los compases seleccionados": "Generate variations of selected measures",
        "Opciones de Variación": "Variation Options",
        "▶ Variaciones Tonales (Notas)": "▶ Tonal Variations (Pitches)",
        "Ninguna:": "None:",
        "Las notas musicales originales se mantienen intactas.": "Original musical notes are kept intact.",
        "Sutil (Baladas / Coros):": "Subtle (Ballads/Choirs):",
        "Movimientos de +/- 1 grado. Notas muy cerca de la original.": "+/- 1 scale degree movements. Very close to the original.",
        "Normal (Estándar):": "Normal (Standard):",
        "Saltos intermedios (1 a 3 grados). Familiaridad y sorpresa.": "Intermediate jumps (1 to 3 degrees). Balance of familiarity and surprise.",
        "Agresivo (Arpegios / Solos):": "Aggressive (Arpeggios/Solos):",
        "Saltos extensos (4 a 5 grados). Transforma la melodía.": "Wide jumps (4 to 5 degrees). Significantly transforms the melody.",
        "Final (Resolutiva):": "Final (Resolving):",
        "Obliga a que la melodía termine (resuelva) en la nota tónica.": "Forces the melody to finish resolving on the root (tonic) note.",
        "▶ Variaciones Dinámicas (Volumen)": "▶ Dynamic Variations (Velocity)",
        "El volumen (dinámica) original se mantiene intacto.": "Original volume (dynamics) is kept intact.",
        "Humanizar:": "Humanize:",
        "Pequeñas variaciones aleatorias para dar un toque humano.": "Small random variations to give a human interpretation touch.",
        "Crescendo:": "Crescendo:",
        "Aumenta progresivamente el volumen desde el principio al fin.": "Progressively increases volume from start to finish.",
        "Diminuendo:": "Diminuendo:",
        "Disminuye progresivamente el volumen desde el principio al fin.": "Progressively decreases volume from start to finish.",
        "Acentuación (Golpe):": "Accent (Punch):",
        "Marca con un volumen muy fuerte los inicios de cada compás.": "Marks the start of each measure with a very strong volume hit.",
        "Configurar opciones de variación": "Configure variation options",
        "▶ Variaciones de Tiempo (Duración)": "▶ Time Variations (Duration)",
        "El ritmo original se mantiene intacto.": "Original rhythm is kept intact.",
        "Rotación:": "Rotation:",
        "Desplaza la secuencia de duraciones.": "Shifts the sequence of durations.",
        "Permutación:": "Permutation:",
        "Reordena aleatoriamente las duraciones dentro del compás.": "Randomly reorders note durations inside the measure.",
        "Duración x2:": "Multiplies the duration (twice as slow).",
        "Duración /2:": "Divides the duration (twice as fast).",
        "Partes": "Parts",
        "PartesDesc": "— Different rhythms per section",
        "PartesLabel": "Parts:",
        "Densidad:": "Density:",
        "Voces:": "Voices:",
        "PartesTitle": "Each digit = number of measures for that part (e.g. 234 → Part A: 2 measures, Part B: 3, Part C: 4)",
        "DensidadTitle": "How to vary the number of notes between parts",
        "Alternado (2↔4↔6…)": "Alternating (2↔4↔6…)",
        "Ascendente (2→4→6…)": "Ascending (2→4→6…)",
        "Descendente (6→4→2…)": "Descending (6→4→2…)",
        "Auto (compás actual)": "Auto (current measure)",
        "VocesTitle": "Rotation of muted voices per part",
        "Todas suenan": "All sound",
        "2 calladas (rotar)": "2 muted (rotate)",
        "1 callada (rotar)": "1 muted (rotate)",
        "Solo (3 calladas)": "Solo (3 muted)",
        "PartesReshuffleTitle": "Choose new random patterns keeping the structure",
        "PartesPreviewDefault": "Type a number (e.g. 234) to see the preview",
        "PartesEmptyWarning": "⚠️ Type digits 1-9 (e.g. 234)",
        "Sin partes": "No parts",
        "compExt": "meas",
        "compases insertados": "measures",
        "insertados en pos.": "inserted at pos.",
        "partesExt": "parts",
        "Rand": "Rand",
        "Generación:": "Generation:",
        "GeneracionTitle": "Choose whether to generate only rhythm, add melody or also dynamics",
        "Solo Ritmo": "Rhythm Only",
        "Ritmo y Melodía": "Rhythm & Melody",
        "n-notas": "{n} notes",
        "Ciclo (Notas):": "Cycle (Notes):",
        "Amp (Max):": "Amp (Max):",
        "Notas:": "Notes:",
        "Seleccionar {n} nota(s)": "Select {n} note(s)",
        "Ver variaciones de silencios para 8 notas": "View silence variations for 8 notes",
        "Silencio de Redonda": "Whole Rest",
        "Rest": "Rest",
        "AlertHarmonize": " Harmonized: {n} measures updated from {v}",
        "AlertChromatic": "The chromatic scale already includes all notes. No adjustment needed.",
        "AlertScaleAdjust": " Adjusted to scale: {n} notes adjusted in {m} measures\nVoice: {v}\nScale: {k} {s}",
        "OndaAmpTitle": "Maximum amplitude in scale steps",
        "OndaCycleTitle": "Cycle length in notes",
        "+ Dinamismo": "+ Dynamism",
        "MIDIIndependent": "Mode: Independent",
        "MIDIDependent": "Mode: Dependent",
        "DuplicateMeasure": "Duplicate measure",
        "SplitVoices": "Split voices into 4 measures",
        "InvertSelection": "Invert Selection",
        "DeleteMeasure": "Delete measure",
        "Soprano": "Soprano",
        "Contralto": "Alto",
        "Tenor": "Tenor",
        "Bajo": "Bass",
        "CompasMidi": "Measure",
        "NotaMidi": "Note",
        "NoMultiVoice": "This measure does not have a multi-voice structure",
        "Revert": "Revert",
        "AddMidi": "Add",
        "ApplyMidi": "Apply",
        "MuteVoice": "Mute {v}",
        "ActivateVoice": "Activate {v}",
        "TooltipX2": "Duplicate selected notes and halve duration",
        "TooltipDiv2": "Combine selected notes (reduce count)",
        "TooltipRotate": "Rotate selected notes (Pitch + Duration)",
        "PeakMidi": "peak",
        "ValleyMidi": "valley",
        "DeshacerCambios": "Undo changes in this measure",
        "SaveLyrics": "Save Lyrics",
        "UpdateDBI": "Update",
        "Limitador de Volumen": "Volume Limiter",
        "Mínimo:": "Minimum:",
        "Máximo:": "Maximum:",
        "Aplicar Límite": "Apply Limit",
        "Voz": "Voice",
        "Nombre": "Name",
        "Instrumento": "Instrument",
        "Nombre de pista": "Track name",
        "Instrumento General (aplica a todas las voces):": "General Instrument (applies to all voices):",
        "Arrastra o selecciona un archivo .musicoli": "Drag or select a .musicoli file",
        "¡Archivo cargado correctamente!": "File loaded successfully!",
        "El archivo no tiene el formato .musicoli o .json válido.": "The file does not have a valid .musicoli or .json format.",
        "Error al leer el archivo. Asegúrate de que es un JSON / .musicoli válido.": "Error reading file. Make sure it is a valid JSON / .musicoli.",
        "StrumTitle": "Arpeggio Intensity",
        "Arpeggio": "Arpeggio",
        "Escalas": "Scales",
        "Acordes": "Chords",
        "Apply chord to selected notes": "Apply chord to selected notes",
        "Tessituras": "Tessituras",
        "Min": "Min",
        "Max": "Max"
    },
    de: {
        "Ritmo": "Rhythmus",
        "Melodía": "Melodie",
        "Dinámica": "Dynamik",
        "Instrumentación": "Instrumente",
        "Composición": "Komposition",
        "Lyrics": "Liedtext",
        "BPM": "BPM",
        "Compás": "Takt",
        "Frase": "Phrase",
        "Empezar": "Starten",
        "Tonalidad": "Tonalität",
        "Borrar compás": "Del",
        "Deshacer": "Rückgängig",
        "Rehacer": "Wiederholen",
        "Soprano": "Sopran",
        "Contralto": "Alt",
        "Tenor": "Tenor",
        "Bajo": "Bass",
        "Loop OFF": "Schleife AUS",
        "Loop ON": "Schleife AN",
        "Resumen": "Zusammenfassung",
        "Editor de Paleta de Tonalidades": "Tonart-Palette-Editor",
        "ZONA DE ARMONIZACIÓN": "HARMONISIERUNGSBEREICH",
        "Armonizar desde esta voz": "Ab dieser Stimme harmonisieren",
        "Ajustar a escala": "An Tonleiter anpassen",
        "Onda (Modulación)": "Welle (Modulation)",
        "Aplicar": "Anwenden",
        "Editor de Lyrics": "Liedtext-Editor",
        "Configuración de lyrics próximamente...": "Liedtext-Konfiguration demnächst...",
        "Mezclador de Volúmenes": "Lautstärke-Mixer",
        "Volumen General": "Gesamtlautstärke",
        "Mezcla por Pistas": "Spurenmischung",
        "Configuración de Instrumentos": "Instrumentenkonfiguration",
        "Instrumento General": "Allgemeines Instrument",
        "Composición por compases": "Taktbasierte Komposition",
        "Nomenclatura": "Nomenklatur",
        "Armonía Diatónica": "Diatonische Harmonie",
        "Métrica": "Taktart",
        "Key": "Tonart",
        "Escala": "Skala",
        "Título de la composición": "Kompositionstitel",
        "Activada": "Aktiviert",
        "Desactivada": "Deaktiviert",
        "Mayor": "Dur",
        "Menor": "Moll",
        "Cromática": "Chromatisch",
        "EmpezarLabel": "Starten →",
        "Copiar": "Kopieren",
        "Pegar": "Einfügen",
        "POS": "POS",
        "COMP": "TAKT",
        "Trasponer": "Transponieren",
        "Ir a posición de cursor": "Zur Cursorposition springen",
        "Ir a compás": "Zum Takt springen",
        "Modo: Dependiente (armonía diatónica)": "Modus: Abhängig (diatonische Harmonie)",
        "Modo: Independiente (manual)": "Modus: Unabhängig (manuell)",
        "Borrar compás o compases seleccionados": "Ausgewählte(n) Takt(e) löschen",
        " Compositor de Estructuras": " Struktur-Komponist",
        "Define la estructura (letras A, B, C...)": "Struktur definieren (Buchstaben A, B, C...)",
        "Generar": "Generieren",
        "Frases Disponibles:": "Verfügbare Phrasen:",
        " Editor de Letras": " Text-Editor",
        "Escribe una sílaba por nota. Usa espacios para separar.": "Eine Silbe pro Note schreiben. Mit Leerzeichen trennen.",
        "Guardar Letra": "Text speichern",
        "Ej: ABBC": "Z.B.: ABBC",
        "Ej: La la la...": "Z.B.: La la la...",
        "Clic para descargar, doble clic para editar": "Klicken zum Herunterladen, Doppelklicken zum Bearbeiten",
        "Variaciones": "Variationen",
        "Actualizar": "Aktualisieren",
        "Acc:": "Aktion:",
        "Modo:": "Modus:",
        "Bio:": "Block:",
        "Cnt:": "Anz:",
        "Amp:": "Amp:",
        "Freq:": "Freq:",
        "Fma:": "Form:",
        "Mn:": "Mn:",
        "Mx:": "Mx:",
        " Onda": " Welle",
        " Dinámica (Volumen)": " Dynamik (Lautstärke)",
        "Generar": "Generieren",
        "Modif": "Modif",
        "Seleccionar número de compases": "Anzahl der Takte auswählen",
        "Todo": "Alle",
        "Img2MelodyTitle": "️ Img2Melody",
        "ImgMelodyOpen": " Öffnen",
        "ImgMelodyInfoTitle": "Informationen zum Algorithmus",
        "ImgMelodyDuration": "Dauer:",
        "ImgMelodyRhythm": "Rhythmus:",
        "Sensible (Dinámico + Silencios Trilipi)": "Sensibel (Dynamisch + Trilipi Pausen)",
        "Relativa (Sensible + Tono Relativo)": "Relativ (Sensibel + Relativer Ton)",
        "Literal (Color a Compás RGB)": "Wörtlich (RGB Farbe zu Takt)",
        "Uniforme (Percusión B/C)": "Einheitlich (Perkussion Bass/Snare)",
        "Basado en Brillo (Trilipi)": "Leuchtkraftbasiert (Trilipi)",
        "Completo (Dinámico + Silencios/Rel.)": "Komplett (Dynamisch + Pausen/Rel.)",
        "Arpegio (Escalera de Extremos)": "Arpeggio (Extremleiter)",
        "ImgMelodySettings": "️ Sensible Einstellungen & Struktur",
        "ImgMelodyStructure": "Struktur (Intro - Mitte - Ende):",
        "ImgMelodySil": "Sil:",
        "ImgMelodyVol": "Vol:",
        "ImgMelodyGenerate": " Generieren",
        "ImgMelodyLogicTitle": " Polyphonische Logik:",
        "Eje X": "X-Achse",
        "Tiempo": "Zeit",
        "Eje Y": "Y-Achse",
        "Voces (SATB)": "Stimmen (SATB)",
        "Brillo": "Helligkeit",
        "Altura": "Tonhöhe",
        "Negro": "Schwarz",
        "Silencio (si activo)": "Stille (wenn aktiv)",
        "Blanco": "Weiß",
        "Nota Larga (si activo)": "Lange Note (wenn aktiv)",
        "Int:": "Int:",
        "Det:": "Det:",
        "ImgMelodyDescArpegio": "S→A / T→B Intervall (Skalenschritte) und Grundlautstärke.",
        "ImgMelodyDescLiteral": "Regelt die Detailgenauigkeit zur Gruppierung von Farben (- Detail = Akkorde, + Detail = schnelle Arpeggien).",
        "ImgMelodyDescSensible": "Definiert Dunkelheitsschwelle (Stille) und Grundlautstärke.",
        "compases": "Takte",
        "Cortar": "️ Ausschneiden",
        "Cortar compases seleccionados": "Ausgewählte Takte ausschneiden",
        "Copiar compases seleccionados": "Ausgewählte Takte kopieren",
        "Pegar compases copiados": "Kopierte Takte einfügen",
        "Seleccionar todos los compases": "Alle Takte auswählen",
        "Añadir un compás a la selección": "Einen Takt zur Auswahl hinzufügen",
        "Eliminar un compás de la selección": "Einen Takt aus der Auswahl entfernen",
        "Duplicar": "Duplizieren",
        "Duplicar compases seleccionados": "Ausgewählte Takte duplizieren",
        "Variaciones": "Variationen",
        "Generar variaciones de los compases seleccionados": "Variationen der ausgewählten Takte generieren",
        "🔥 Opciones de Variación": "🔥 Variationsoptionen",
        "▶ Variaciones Tonales (Notas)": "▶ Tonale Variationen (Tonhöhen)",
        "Ninguna:": "Keine:",
        "Las notas musicales originales se mantienen intactas.": "Die ursprünglichen Musiknoten bleiben intakt.",
        "Sutil (Baladas / Coros):": "Subtil (Balladen/Chöre):",
        "Movimientos de +/- 1 grado. Notas muy cerca de la original.": "+/- 1 Skalenschritt Bewegung. Sehr nah am Original.",
        "Normal (Estándar):": "Normal (Standard):",
        "Saltos intermedios (1 a 3 grados). Familiaridad y sorpresa.": "Mittlere Sprünge (1 bis 3 Grad). Gleichgewicht aus Vertrautem und Überraschung.",
        "Agresivo (Arpegios / Solos):": "Aggressiv (Arpeggios/Solos):",
        "Saltos extensos (4 a 5 grados). Transforma la melodía.": "Weite Sprünge (4 bis 5 Grad). Verwandelt die Melodie erheblich.",
        "Final (Resolutiva):": "Final (Auflösend):",
        "Obliga a que la melodía termine (resuelva) en la nota tónica.": "Zwingt die Melodie, auf dem Grundton (Tonika) aufzulösen.",
        "▶ Variaciones Dinámicas (Volumen)": "▶ Dynamische Variationen (Lautstärke)",
        "El volumen (dinámica) original se mantiene intacto.": "Ursprüngliche Lautstärke (Dynamik) bleibt intakt.",
        "Humanizar:": "Humanisieren:",
        "Pequeñas variaciones aleatorias para dar un toque humano.": "Kleine zufällige Variationen, um eine menschliche Interpretation zu verleihen.",
        "Crescendo:": "Crescendo:",
        "Aumenta progresivamente el volumen desde el principio al fin.": "Erhöht die Lautstärke von Anfang bis Ende schrittweise.",
        "Diminuendo:": "Diminuendo:",
        "Disminuye progresivamente el volumen desde el principio al fin.": "Verringert die Lautstärke von Anfang bis Ende schrittweise.",
        "Acentuación (Golpe):": "Betonung (Schlag):",
        "Marca con un volumen muy fuerte los inicios de cada compás.": "Markiert den Beginn jedes Taktes mit einem sehr starken Lautstärkeschlag.",
        "Configurar opciones de variación": "Variationsoptionen konfigurieren",
        "▶ Variaciones de Tiempo (Duración)": "▶ Zeitvariationen (Dauer)",
        "El ritmo original se mantiene intacto.": "Der ursprüngliche Rhythmus bleibt intakt.",
        "Rotación:": "Rotation:",
        "Desplaza la secuencia de duraciones.": "Verschiebt die Abfolge der Dauern.",
        "Permutación:": "Permutation:",
        "Reordena aleatoriamente las duraciones dentro del compás.": "Ordnet die Notendauern innerhalb des Taktes zufällig neu an.",
        "Duración x2:": "Multipliziert die Dauer (doppelt so langsam).",
        "Duración /2:": "Unterteilt die Dauer (doppelt so schnell).",
        "Partes": "Teile",
        "PartesDesc": "— Verschiedene Rhythmen pro Abschnitt",
        "PartesLabel": "Teile:",
        "Densidad:": "Dichte:",
        "Voces:": "Stimmen:",
        "PartesTitle": "Jede Ziffer = Anzahl der Takte für diesen Teil (z.B. 234 → Teil A: 2 Takte, Teil B: 3, Teil C: 4)",
        "DensidadTitle": "Wie die Anzahl der Noten zwischen den Teilen variiert wird",
        "Alternado (2↔4↔6…)": "Abwechselnd (2↔4↔6…)",
        "Ascendente (2→4→6…)": "Aufsteigend (2→4→6…)",
        "Descendente (6→4→2…)": "Absteigend (6→4→2…)",
        "Auto (compás actual)": "Auto (aktueller Takt)",
        "VocesTitle": "Rotation der stummgeschalteten Stimmen pro Teil",
        "Todas suenan": "Alle klingen",
        "2 calladas (rotar)": "2 stumm (rotieren)",
        "1 callada (rotar)": "1 stumm (rotieren)",
        "Solo (3 calladas)": "Solo (3 stumm)",
        "PartesReshuffleTitle": "Neue zufällige Muster bei gleicher Struktur wählen",
        "PartesPreviewDefault": "Zahl eingeben (z.B. 234) um die Vorschau zu sehen",
        "PartesEmptyWarning": "⚠️ Ziffern 1-9 eingeben (z.B. 234)",
        "Sin partes": "Keine Teile",
        "compExt": "Takt",
        "compases insertados": "Takte",
        "insertados en pos.": "eingefügt an pos.",
        "partesExt": "Teile",
        "Rand": "Rand",
        "Generación:": "Generierung:",
        "GeneracionTitle": "Wählen Sie, ob nur Rhythmus, Melodie oder auch Dynamik erzeugt werden soll",
        "Solo Ritmo": "Nur Rhythmus",
        "Ritmo y Melodía": "Rhythmus & Melodie",
        "+ Dinamismo": "+ Dynamik",
        "Limitador de Volumen": "Lautstärkebegrenzer",
        "Mínimo:": "Minimum:",
        "Máximo:": "Maximal:",
        "Aplicar Límite": "Limit anwenden",
        "Voz": "Stimme",
        "Nombre": "Name",
        "Instrumento": "Instrument",
        "Nombre de pista": "Spurname",
        "Instrumento General (aplica a todas las voces):": "Allgemeines Instrument (gilt für alle Stimmen):",
        "Arrastra o selecciona un archivo .musicoli": "Ziehen oder wählen Sie eine .musicoli-Datei",
        "¡Archivo cargado correctamente!": "Datei erfolgreich geladen!",
        "El archivo no tiene el formato .musicoli o .json válido.": "Die Datei hat kein gültiges .musicoli- oder .json-Format.",
        "Error al leer el archivo. Asegúrate de que es un JSON / .musicoli válido.": "Fehler beim Lesen der Datei. Stellen Sie sicher, dass es ein gültiges JSON / .musicoli ist.",
        "StrumTitle": "Arpeggio-Intensität",
        "Arpeggio": "Arpeggio",
        "Tessituras": "Tonumfänge",
        "Min": "Min",
        "Max": "Max"
    }
};

let currentLanguage = 'en';

function setLanguage(lang) {
    if (LANGUAGES[lang]) {
        currentLanguage = lang;
        applyTranslations();
    }
}

function t(key) {
    return LANGUAGES[currentLanguage][key] || key;
}

function applyTranslations() {
    // Translate elements with data-i18n attribute
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (key) {
            el.textContent = t(key);
        }
    });

    // Translate elements with data-i18n-placeholder attribute
    const placeholderElements = document.querySelectorAll('[data-i18n-placeholder]');
    placeholderElements.forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (key) {
            el.placeholder = t(key);
        }
    });

    // Translate elements with data-i18n-title attribute
    const titleElements = document.querySelectorAll('[data-i18n-title]');
    titleElements.forEach(el => {
        const key = el.getAttribute('data-i18n-title');
        if (key) {
            el.title = t(key);
        }
    });

    // Translate specific buttons by ID (legacy support / if data-i18n not added yet)
    // We will add logic here or prefer using data-i18n in HTML

    // Translate specific buttons by ID (legacy support / if data-i18n not added yet)
    // We will add logic here or prefer using data-i18n in HTML

    console.log(`Language set to ${currentLanguage}`);
}

// Apply English translations immediately on load (preferences.js may override later with saved language)
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => applyTranslations());
} else {
    applyTranslations();
}
